# Generated by Django 4.2.9 on 2026-06-28 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bet_matches/')),
                ('points_reward', models.IntegerField(default=100)),
                ('on_chain_match_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('result', models.CharField(blank=True, choices=[('team1', 'Team 1 Win'), ('team2', 'Team 2 Win'), ('draw', 'Draw')], max_length=10, null=True)),
                ('team1_name', models.CharField(default='Team 1', max_length=100)),
                ('team2_name', models.CharField(default='Team 2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BetVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('team1', 'Team 1 Win'), ('team2', 'Team 2 Win'), ('draw', 'Draw')], max_length=10)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='bets.betmatch')),
            ],
        ),
    ]
